version: '3'

services:

  broker:
    container_name: mqtt_broker
    build: broker
    networks:
      - backend
    
  mariadb:
    container_name: database
    image: mariadb:10.2
    restart: 'always'
    volumes: 
      - ./database/data:/var/lib/mysql
      - ./database/logs:/var/log/mysql
      - ./database/conf:/etc/mysql
      - ./database/scripts:/home/src
    environment:
      MYSQL_ROOT_PASSWORD: "p@ss_123"
      MYSQL_DATABASE: "hotel"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "p@ss"
    networks:
      - backend

  webserver:
    container_name: webserver
    image: httpd:2.4
 
  api:
    container_name: fastapi
    build: api
    restart: 'always'
    volumes:
      - ./api/code:/code/app
    environment:
      - PYTHONUNBUFFERED=0
    networks:
      - backend
    ports:
      - "8080:80" 
    entrypoint:
      - "uvicorn"
      - "app.api:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "80"
    depends_on:
      - database
    
 
  management_node:
    container_name: mgmt
    build: mn
    volumes:
      - ./mn/src:/home/src
    environment:
      - PYTHONUNBUFFERED=0
    working_dir: /home/src  
    entrypoint:
      - sleep
      - 1d
    networks:
      - backend
 
networks:    
    backend:
        driver: bridge
  