version: '2'

services:

  broker:
    container_name: mqtt_broker
    build: broker
    
  database:
    container_name: database
    image: mariadb
    entrypoint:
      - sleep
      - 1d
    
  webserver:
    container_name: webserver
    build: http
 
  api:
    container_name: fastapi
    build: api
    volumes:
      - ./api/code:/code/app
    environment:
      - PYTHONUNBUFFERED=0
    ports:
      - "8080:80" 
    entrypoint:
      - "uvicorn"
      - "app.api:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "80"
 
  management_node:
    container_name: management_node
    build: mn
    volumes:
      - ./mn/src:/home/src
    environment:
      - PYTHONUNBUFFERED=0
    working_dir: /home/src  
    entrypoint:
      - sleep
      - 1d
  